#define BUTTON 39 
#define BUTTON_1 10
#define BUTTON_2 11
#define BUTTON_3 12
#define SCROLL_UP 27
#define SCROLL_DOWN 41 
#define KEY_LEFT_UP 24
#define KEY_UP 25
#define KEY_RIGHT_UP 26 
#define KEY_LEFT 38 
#define KEY_RIGHT 40
#define KEY_LEFT_DOWN 52
#define KEY_DOWN 53
#define KEY_RIGHT_DOWN 54 
#define KEY_ESC 9 
#define BASE_SPEED 4 
#define GROWTH_RATIO 4 
#define OBLIQUE_RATE 0.7
#define MAX_SPEED 100
#define START 148

